INSERT INTO PRODUCTS (NAME, CURRENT_PRICE)
    VALUES ('HTC 10 EVO', 74.99);
INSERT INTO PRODUCTS (NAME, CURRENT_PRICE)
    VALUES ('Samsung Galaxy Note 8', 324.99);
INSERT INTO PRODUCTS (NAME, CURRENT_PRICE)
    VALUES ('Samsung Galaxy S9 G960U', 449.99);
INSERT INTO PRODUCTS (NAME, CURRENT_PRICE)
    VALUES ('LG G Vista D631', 59.95);